# Generated by Django 4.0.4 on 2022-05-02 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uesr_id', models.IntegerField()),
                ('login_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('sex', models.IntegerField()),
                ('vege_type', models.CharField(max_length=30)),
                ('alle_type', models.CharField(max_length=50)),
                ('metabolism', models.IntegerField()),
            ],
        ),
    ]
