# Generated by Django 4.0.4 on 2022-05-02 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a4app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uesr_id',
            new_name='user_id',
        ),
    ]
